### ISSUE TITLE
Transparent button in wireframes

### ISSUE THREAD

**Issue by Liangda-w** [luileito/enrico#2]
Hi, I've noticed that in wireframes the buttons are transparent, 
i.e. for the image processing they won't be identified (for example 514) 

So is there any suggested way to make those buttons non-transparent? Thanks!

**Comment by luileito** [comment]
Hi, good catch! You can flatten the PNG images so that the button color becomes white.

**Comment by Liangda-w** [comment]
Thx for your answer! But in this way I will lose this information on the image, is there a way to give it a color?

**Comment by luileito** [comment]
Yes, you can use the color specified in `component_legend.json` if you want.

**Comment by Liangda-w** [comment]
Okay, thanks!
